##current app conf
name: "weber"
mode: "dev"
port: 8888
version: "v1.0.0"
start_time: "2020-07-01"
machine_id: 1

log:
  level: "debug"
  filename: "weber.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  user: "root"
  port: 3306
  password: "123456"
  dbname: "weber"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100

