app:
  name: "weber"
  mode: "dev"
  port: 8081
  version: "v1.0.0"

log:
  level: "debug"
  filename: "weber.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  user: "root"
  port: 3306
  password: "123456"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100

